# -*- coding: utf-8 -*-

import logging
import secrets

from odoo import api, fields, models, _
from odoo.exceptions import AccessError

_logger = logging.getLogger(__name__)


class ResConfigSettings(models.TransientModel):
    _inherit = 'res.config.settings'

    # -- Retention --
    audit_retention_days = fields.Integer(
        string='Log Retention (Days)',
        default=365,
        config_parameter='audit_security_sentinel.retention_days',
        help=(
            'Number of days to keep audit log records. '
            'Logs older than this will be purged by the retention cron.'
        ),
    )

    # -- Hash salt (display only) --
    audit_hash_salt_display = fields.Char(
        string='Current Hash Salt',
        compute='_compute_audit_hash_salt_display',
        help=(
            'First 8 characters of the active hash salt, shown for '
            'verification purposes. The full salt is never exposed.'
        ),
    )

    # -- Dashboard auto-refresh --
    audit_dashboard_refresh = fields.Integer(
        string='Dashboard Refresh Interval (s)',
        default=60,
        config_parameter='audit_security_sentinel.dashboard_refresh_interval',
        help='Auto-refresh interval in seconds for the real-time audit dashboard.',
    )

    # ----------------------------------------------------------------
    # Compute
    # ----------------------------------------------------------------
    @api.depends_context('uid')
    def _compute_audit_hash_salt_display(self):
        """Show a masked preview of the hash salt for verification."""
        ICP = self.env['ir.config_parameter'].sudo()
        salt = ICP.get_param('audit_security_sentinel.hash_salt', default='')
        masked = f"{salt[:8]}..." if len(salt) > 8 else salt or _('Not configured')
        for record in self:
            record.audit_hash_salt_display = masked

    # ----------------------------------------------------------------
    # Actions
    # ----------------------------------------------------------------
    def action_regenerate_salt(self):
        """Generate a new cryptographic salt and store it in system parameters.

        WARNING: This invalidates the integrity hash of every existing
        audit.log record. Use only when strictly necessary.
        """
        self.ensure_one()
        if not self.env.user.has_group('audit_security_sentinel.group_audit_manager'):
            raise AccessError(_('Only Compliance Officers can regenerate the hash salt.'))
        new_salt = secrets.token_hex(32)
        self.env['ir.config_parameter'].sudo().set_param(
            'audit_security_sentinel.hash_salt', new_salt,
        )
        # Invalidate in-memory salt cache so the new salt is used immediately
        from .audit_hook import invalidate_salt_cache
        invalidate_salt_cache()
        _logger.warning(
            "Security Sentinel: Hash salt regenerated by uid=%s. "
            "All existing audit hashes are now invalid.",
            self.env.uid,
        )
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Salt Regenerated'),
                'message': _(
                    'A new hash salt has been generated. '
                    'All previously computed integrity hashes are now invalid.'
                ),
                'type': 'warning',
                'sticky': True,
            },
        }
